apiVersion: v1
kind: Service
metadata:
  namespace: ckan
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ckan2pycsw
  name: ckan2pycsw
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  type: NodePort
  selector:
    io.kompose.service: ckan2pycsw
