apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan2pycsw-pvc-log
  namespace: ckan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default