FROM python:3.11.5-slim-bullseye
LABEL maintainer="mnl.janez@gmail.com"

# Production non-root user
ENV USERNAME=ckan-pycsw
ENV USER_UID=10001
ENV USER_GID=$USER_UID
# ckan-pycsw envvars
ENV APP_DIR=/app
ENV TZ=UTC
RUN echo ${TZ} > /etc/timezone
ENV PYCSW_CKAN_SCHEMA=iso19139_inspire
ENV PYCSW_CONFIG=${APP_DIR}/pycsw.conf
ENV CKAN_URL=http://localhost:5000/
ENV PYCSW_PORT=8880
ENV PYCSW_URL=http://localhost:${PYCSW_PORT}/
ENV DEV_MODE=True
ENV PYCSW_DEV_PORT=5678
ENV TIMEOUT=300

RUN apt-get -q -y update && apt-get install -y --no-install-recommends \
        wget \
        gettext-base \
        procps && \
    wget --progress=dot:mega -O /wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for && \
    chmod +x /wait-for && \
    python3 -m pip install --no-cache-dir pdm==2.9.2 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR ${APP_DIR}

COPY pyproject.toml pdm.lock ./

RUN pdm install --no-self --group prod

COPY ckan-pycsw/conf/pycsw.conf.template ckan-pycsw/docker-entrypoint.d/entrypoint_dev.sh ./
COPY ckan2pycsw ckan2pycsw

EXPOSE ${PYCSW_PORT}/TCP
EXPOSE ${PYCSW_DEV_PORT}/TCP

USER $USERNAME

# Set entrypoint with debugpy
ENTRYPOINT ["/bin/bash", "-c", "python3 -m debugpy --listen 0.0.0.0:${PYCSW_DEV_PORT} --wait-for-client ./entrypoint_dev.sh"]
CMD ["pdm", "run", "python3", "-m", "gunicorn", "pycsw.wsgi:application", "-b", "0.0.0.0:${PYCSW_PORT}"]