# Base image
FROM ghcr.io/mjanez/ckan-pycsw:main AS base
LABEL maintainer="mnl.janez@gmail.com"

# ckan-pycsw envvars
ENV APP_DIR=/app
ENV TZ=UTC
ENV PYCSW_CKAN_SCHEMA=iso19139_inspire
ENV PYCSW_CONFIG=${APP_DIR}/pycsw.conf
ENV CKAN_URL=http://localhost:5000/
ENV PYCSW_PORT=8000
ENV PYCSW_URL=http://localhost:${PYCSW_PORT}/
ENV DEV_MODE=True
ENV PYCSW_DEV_PORT=5678
ENV TIMEOUT=300

WORKDIR ${APP_DIR}

# Update files if needed
COPY ckan-pycsw/docker-entrypoint.d/entrypoint_dev.sh /app/docker-entrypoint.d/
COPY ckan2pycsw /

USER root

# Install dependencies for development mode
RUN apt-get -q -y update && apt-get install -y --no-install-recommends \
        procps=2:3.3.17-5 && \
    python3 -m pip install --no-cache-dir \
        debugpy==1.8.0 && \
    rm -rf /var/lib/apt/lists/*

USER $USERNAME

ENTRYPOINT ["/bin/bash", "-c", "python3 -m debugpy --listen 0.0.0.0:${PYCSW_DEV_PORT} --wait-for-client ./docker-entrypoint.d/entrypoint_dev.sh"]
CMD ["pdm", "run", "python3", "-m", "gunicorn", "pycsw.wsgi:application", "-b", "0.0.0.0:${PYCSW_PORT}"]